### ISSUE TITLE
If the name of the png file contains space ' ', operation will be faild

### ISSUE THREAD

**Issue by ghost** [TinoGuo/AnimatedWebp#1]
If the path of the png file contains any space charater, the tool will stop working and throw an error message to me.
private static String encodeWebpCmd = "%s/cwebp -q %d %s -o %s";
private static String webpMuxCmd = "%s/webpmux %s -loop %d -bgcolor 0,0,0,0 -o %s.webp";
private static String singleWebpCmd = "%s/cwebp -q %d %s -o %s";
It will be fine if you update those CMD text.

**Comment by TinoGuo** [comment]
@polaris-zx this library I will not maintenance in the future, you can move to [https://github.com/TinoGuo/AnimatedWebp2](url) written in Kotlin. I will fix this bug at that library.
Thanks!😁
